### ISSUE TITLE
protobuf dependency problem, forbid v3.11

### ISSUE THREAD

**Issue by bigredpandas** [conda-forge/streamlit-feedstock#15]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Hello streamlit-team,

great work and I love your app! 

I recently wanted to clean up my environment and wanted to move streamlit and its dependencies, that I installed with pip, to conda.

I am unable to successfully run streamlit using conda (see error code below with details). The reason is that conda installs the wrong version of the Streamlit dependency protobuf, it installs v 3.11.xx. This issue is described here (https://github.com/streamlit/streamlit/issues/2234) and was fixed in the pip file of the Streamlit source code (https://github.com/streamlit/streamlit/commit/9a2059ecf1ff3a17cc3dda274f207b8f2f0b8b37#diff-ca44356d7dea05bd28bbce233d0c1924f03044f68f40b5d609ef0178ca03f06e).

I think in the recipe/meta.yaml file the same fix needs to be made as in the pip file:
this
<code>    - protobuf >=3.6.0</code>
should be this
<code>    - protobuf >=3.6.0, !=3.11</code>

I made a pull request, but I am not an expert (this is my first issue filing), it is just my guess.

I tried to manually force conda to install a different version <code>conda install protobuf=3.10.1=py38h0a44026_0</code>, but I am getting conflicts.

<br/>
Details of error code when running <code> streamlit hello </code>
<details>
<code>
(ml-datascience) janbiederbeck@Air-von-Jan ev-analysis % streamlit hello
Traceback (most recent call last):
  File "/Users/janbiederbeck/opt/anaconda3/envs/ml-datascience/bin/streamlit", line 6, in <module>
    from streamlit.cli import main
  File "/Users/janbiederbeck/opt/anaconda3/envs/ml-datascience/lib/python3.8/site-packages/streamlit/__init__.py", line 52, in <module>
    from streamlit.proto.RootContainer_pb2 import RootContainer
  File "/Users/janbiederbeck/opt/anaconda3/envs/ml-datascience/lib/python3.8/site-packages/streamlit/proto/RootContainer_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
</code>
</details>

<br/>
Environment (<code>conda list</code>):
<details>

```
# Name                    Version                   Build  Channel
_anaconda_depends         2020.07                  py38_0  
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0  
abseil-cpp                20200225.2           hb1e8313_1    conda-forge
alabaster                 0.7.12             pyhd3eb1b0_0  
altair                    4.1.0                      py_1  
anaconda                  custom                   py38_1  
anaconda-client           1.7.2                    py38_0  
anaconda-navigator        1.10.0                   py38_0  
anaconda-project          0.9.1              pyhd3eb1b0_1  
anyio                     2.2.0            py38hecd8cb5_0  
appdirs                   1.4.4                      py_0  
applaunchservices         0.2.1                      py_0  
appnope                   0.1.2           py38hecd8cb5_1001  
appscript                 1.1.2            py38h9ed2024_0  
argh                      0.26.2                   py38_0  
argon2-cffi               20.1.0           py38h9ed2024_1  
arrow-cpp                 3.0.0            py38hf7c73f6_3  
asn1crypto                1.4.0                      py_0  
astor                     0.8.1            py38hecd8cb5_0  
astroid                   2.5              py38hecd8cb5_1  
astropy                   4.2              py38h9ed2024_0  
async_generator           1.10               pyhd3eb1b0_0  
atomicwrites              1.4.0                      py_0  
attrs                     20.3.0             pyhd3eb1b0_0  
autopep8                  1.5.6              pyhd3eb1b0_0  
aws-c-common              0.4.57               hb1e8313_1  
aws-c-event-stream        0.1.6                h23ab428_5  
aws-checksums             0.1.9                hb1e8313_0  
aws-sdk-cpp               1.8.156              he271ece_0  
babel                     2.9.0              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
backports                 1.0                pyhd3eb1b0_2  
backports.functools_lru_cache 1.6.1              pyhd3eb1b0_0  
backports.shutil_get_terminal_size 1.0.0              pyhd3eb1b0_3  
backports.tempfile        1.0                pyhd3eb1b0_1  
backports.weakref         1.0.post1                  py_1  
base58                    2.1.0              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.9.3              pyha847dfd_0  
bitarray                  1.7.1            py38h9ed2024_1  
bkcharts                  0.2                      py38_0  
black                     19.10b0                    py_0  
blas                      1.0                         mkl  
bleach                    3.3.0              pyhd3eb1b0_0  
blinker                   1.4              py38hecd8cb5_0  
blosc                     1.21.0               h2842e9f_0  
bokeh                     2.3.0            py38hecd8cb5_0  
boost-cpp                 1.73.0              h9ed2024_11  
boto                      2.49.0                   py38_0  
boto3                     1.17.28            pyhd3eb1b0_0  
botocore                  1.20.30            pyhd3eb1b0_1  
bottleneck                1.3.2            py38hf1fa96c_1  
brotli                    1.0.9                hb1e8313_2  
brotlipy                  0.7.0           py38h9ed2024_1003  
brunsli                   0.1                  h23ab428_0  
bzip2                     1.0.8                h1de35cc_0  
c-ares                    1.17.1               h9ed2024_0  
ca-certificates           2021.1.19            hecd8cb5_1  
cachetools                4.2.1              pyhd3eb1b0_0  
certifi                   2020.12.5        py38hecd8cb5_0  
cffi                      1.14.5           py38h2125817_0  
chardet                   4.0.0           py38hecd8cb5_1003  
charls                    2.1.0                hb1e8313_2  
click                     7.1.2              pyhd3eb1b0_0  
cloudpickle               1.6.0                      py_0  
clyent                    1.2.2                    py38_1  
colorama                  0.4.4              pyhd3eb1b0_0  
conda-package-handling    1.7.2            py38h22f3db7_0  
conda-verify              3.4.2                      py_1  
contextlib2               0.6.0.post1                py_0  
cryptography              3.4.6            py38h2fd3fbb_0  
curl                      7.71.1               hb0a8c7a_1  
cycler                    0.10.0                   py38_0  
cython                    0.29.22          py38h23ab428_0  
cytoolz                   0.11.0           py38haf1e3a3_0  
dask                      2021.3.0           pyhd3eb1b0_0  
dask-core                 2021.3.0           pyhd3eb1b0_0  
dbus                      1.13.18              h18a8e69_0  
decorator                 4.4.2              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713                   py_0  
distributed               2021.3.0         py38hecd8cb5_0  
docutils                  0.16                     py38_1  
double-conversion         3.1.5                haf313ee_1  
entrypoints               0.3                      py38_0  
et_xmlfile                1.0.1                   py_1001  
expat                     2.2.10               hb1e8313_2  
fastcache                 1.1.0            py38h1de35cc_0  
filelock                  3.0.12             pyhd3eb1b0_1  
flake8                    3.9.0              pyhd3eb1b0_0  
flask                     1.1.2              pyhd3eb1b0_0  
freetype                  2.10.4               ha233b18_0  
fsspec                    0.8.3                      py_0  
future                    0.18.2                   py38_1  
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             hb0f4f8b_2  
gevent                    21.1.1           py38h9ed2024_1  
gflags                    2.2.2                h0a44026_0  
giflib                    5.1.4                h1de35cc_1  
gitdb                     4.0.5                      py_0  
gitpython                 3.1.14             pyhd3eb1b0_1  
glib                      2.67.4               hdf23fa2_1  
glob2                     0.7                pyhd3eb1b0_0  
glog                      0.4.0                h0a44026_0  
gmp                       6.2.1                h23ab428_2  
gmpy2                     2.0.8            py38h6ef4df4_3  
greenlet                  1.0.0            py38h23ab428_2  
grpc-cpp                  1.29.0               h0284957_0    conda-forge
h5py                      2.10.0           py38h3134771_0  
hdf5                      1.10.4               hfa1e0ec_0  
heapdict                  1.0.1                      py_0  
html5lib                  1.1                        py_0  
icu                       58.2                 h0a44026_3  
idna                      2.10               pyhd3eb1b0_0  
imagecodecs               2021.1.11        py38h2ea9c00_1  
imageio                   2.9.0                      py_0  
imagesize                 1.2.0              pyhd3eb1b0_0  
importlib-metadata        3.7.3            py38hecd8cb5_1  
importlib_metadata        3.7.3                hd3eb1b0_1  
iniconfig                 1.1.1              pyhd3eb1b0_0  
intel-openmp              2019.4                      233  
intervaltree              3.1.0                      py_0  
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   7.21.0           py38h01d92e1_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.3              pyhd3eb1b0_1  
isort                     5.7.0              pyhd3eb1b0_0  
itsdangerous              1.1.0              pyhd3eb1b0_0  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.4.1                      py_0  
jedi                      0.17.2           py38hecd8cb5_1  
jinja2                    2.11.3             pyhd3eb1b0_0  
jmespath                  0.10.0                     py_0  
joblib                    1.0.1              pyhd3eb1b0_0  
jpeg                      9b                   he5867d9_2  
json5                     0.9.5                      py_0  
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0                    py38_7  
jupyter-packaging         0.7.12             pyhd3eb1b0_0  
jupyter_client            6.1.7                      py_0  
jupyter_console           6.3.0              pyhd3eb1b0_0  
jupyter_core              4.7.1            py38hecd8cb5_0  
jupyter_server            1.4.1            py38hecd8cb5_0  
jupyterlab                3.0.12             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.3.0              pyhd3eb1b0_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
jxrlib                    1.1                  haf1e3a3_2  
keyring                   22.3.0           py38hecd8cb5_0  
kiwisolver                1.3.1            py38h23ab428_0  
krb5                      1.18.2               h75d18d8_0  
lazy-object-proxy         1.5.2            py38h9ed2024_0  
lcms2                     2.11                 h92f6f08_0  
lerc                      2.2.1                h23ab428_0  
libaec                    1.0.4                hb1e8313_1  
libarchive                3.4.2                haa3ed63_0  
libboost                  1.73.0              hd4c2dcd_11  
libcurl                   7.71.1               h8a08a2b_1  
libcxx                    10.0.0                        1  
libdeflate                1.7                  h9ed2024_5  
libedit                   3.1.20210216         h9ed2024_1  
libevent                  2.1.8                hddc9c9b_1  
libffi                    3.3                  hb1e8313_2  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.16                 h1de35cc_0  
liblief                   0.10.1               h0a44026_0  
libllvm10                 10.0.1               h76017ad_5  
libllvm9                  9.0.1                h21ff451_1  
libpng                    1.6.37               ha441bb4_0  
libprotobuf               3.11.4               hd9629dc_0  
libsodium                 1.0.18               h1de35cc_0  
libspatialindex           1.9.3                h23ab428_0  
libssh2                   1.9.0                ha12b0ac_1  
libthrift                 0.13.0               h054ceb0_6  
libtiff                   4.1.0                hcb84e12_1  
libwebp                   1.0.1                hd73b212_0  
libxml2                   2.9.10               h7cdb67c_3  
libxslt                   1.1.34               h83b36ba_0  
libzopfli                 1.0.3                hb1e8313_0  
llvm-openmp               10.0.0               h28b9765_0  
llvmlite                  0.36.0           py38he4411ff_4  
locket                    0.2.1            py38hecd8cb5_1  
lxml                      4.6.2            py38h26b266a_0  
lz4-c                     1.9.3                h23ab428_0  
lzo                       2.10                 haf1e3a3_2  
markupsafe                1.1.1            py38h1de35cc_1  
matplotlib                3.3.4            py38hecd8cb5_0  
matplotlib-base           3.3.4            py38h8b3ea08_0  
mccabe                    0.6.1                    py38_1  
mistune                   0.8.4           py38h1de35cc_1001  
mkl                       2019.4                      233  
mkl-service               2.3.0            py38h9ed2024_0  
mkl_fft                   1.3.0            py38ha059aab_0  
mkl_random                1.1.1            py38h959d312_0  
mock                      4.0.3              pyhd3eb1b0_0  
more-itertools            8.7.0              pyhd3eb1b0_0  
mpc                       1.1.0                h6ef4df4_1  
mpfr                      4.0.2                h9066e36_1  
mpmath                    1.1.0                    py38_0  
msgpack-python            1.0.2            py38hf7b0b51_1  
multipledispatch          0.6.0                    py38_0  
mypy_extensions           0.4.3                    py38_0  
navigator-updater         0.2.1                    py38_0  
nbclassic                 0.2.6              pyhd3eb1b0_0  
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.0.7                    py38_0  
nbformat                  5.1.2              pyhd3eb1b0_1  
ncurses                   6.2                  h0a44026_1  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
networkx                  2.5                        py_0  
nltk                      3.5                        py_0  
nodejs                    10.13.0              h0a44026_0  
nose                      1.3.7           pyhd3eb1b0_1006  
notebook                  6.2.0            py38hecd8cb5_0  
numba                     0.53.0           py38hb2f4e1b_0  
numexpr                   2.7.3            py38h16bde0e_0  
numpy                     1.19.2           py38h456fd55_0  
numpy-base                1.19.2           py38hcfb5961_0  
numpydoc                  1.1.0              pyhd3eb1b0_1  
olefile                   0.46                       py_0  
openjpeg                  2.3.0                hb95cd4c_1  
openpyxl                  3.0.7              pyhd3eb1b0_0  
openssl                   1.1.1j               h9ed2024_0  
orc                       1.6.5                h001ef8f_1  
packaging                 20.9               pyhd3eb1b0_0  
pandas                    1.2.3            py38hb2f4e1b_0  
pandoc                    2.12                 hecd8cb5_0  
pandocfilters             1.4.3            py38hecd8cb5_1  
parso                     0.7.0                      py_0  
partd                     1.1.0                      py_0  
path                      15.1.2           py38hecd8cb5_0  
path.py                   12.5.0                        0  
pathlib2                  2.3.5            py38hecd8cb5_2  
pathspec                  0.7.0                      py_0  
pathtools                 0.1.2                      py_1  
patsy                     0.5.1                    py38_0  
pcre                      8.44                 hb1e8313_0  
pep8                      1.7.1                    py38_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.1.2            py38h5270095_0  
pip                       21.0.1           py38hecd8cb5_0  
pkginfo                   1.7.0            py38hecd8cb5_0  
plotly                    4.14.3             pyhd3eb1b0_0  
pluggy                    0.13.1           py38hecd8cb5_0  
ply                       3.11                     py38_0  
prometheus_client         0.9.0              pyhd3eb1b0_0  
prompt-toolkit            3.0.8                      py_0  
prompt_toolkit            3.0.8                         0  
protobuf                  3.11.4           py38hc84c608_1    conda-forge
psutil                    5.8.0            py38h9ed2024_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
py                        1.10.0             pyhd3eb1b0_0  
py-lief                   0.10.1           py38haf313ee_0  
pyarrow                   3.0.0            py38hdf3e9eb_3  
pycodestyle               2.6.0              pyhd3eb1b0_0  
pycosat                   0.6.3            py38h1de35cc_1  
pycparser                 2.20                       py_2  
pycurl                    7.43.0.6         py38hddc9c9b_0  
pydeck                    0.5.0              pyh9f0ad1d_0    conda-forge
pydocstyle                5.1.1                      py_0  
pyerfa                    1.7.2            py38h9ed2024_0  
pyflakes                  2.2.0              pyhd3eb1b0_0  
pygments                  2.8.1              pyhd3eb1b0_0  
pylint                    2.7.2            py38hecd8cb5_1  
pyls-black                0.4.6                hd3eb1b0_0  
pyls-spyder               0.3.2              pyhd3eb1b0_0  
pyodbc                    4.0.30           py38h0a44026_0  
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py38h655552a_2  
pyrsistent                0.17.3           py38haf1e3a3_0  
pysocks                   1.7.1                    py38_1  
pytables                  3.6.1            py38h4727e94_0  
pytest                    6.2.2            py38hecd8cb5_2  
python                    3.8.8                h88f2d9e_4  
python-dateutil           2.8.1              pyhd3eb1b0_0  
python-jsonrpc-server     0.4.0                      py_0  
python-language-server    0.36.2             pyhd3eb1b0_0  
python-libarchive-c       2.9                pyhd3eb1b0_0  
python.app                3                py38h9ed2024_0  
python_abi                3.8                      1_cp38    conda-forge
pytz                      2021.1             pyhd3eb1b0_0  
pywavelets                1.1.1            py38haf1e3a3_2  
pyyaml                    5.4.1            py38h9ed2024_1  
pyzmq                     20.0.0           py38h23ab428_1  
qdarkstyle                2.8.1                      py_0  
qt                        5.9.7                h468cd18_1  
qtawesome                 1.0.2              pyhd3eb1b0_0  
qtconsole                 5.0.2              pyhd3eb1b0_0  
qtpy                      1.9.0                      py_0  
re2                       2020.11.01           h23ab428_1  
readline                  8.1                  h9ed2024_0  
regex                     2021.3.17        py38h9ed2024_0  
requests                  2.25.1             pyhd3eb1b0_0  
retrying                  1.3.3                      py_2  
ripgrep                   12.1.1                        0  
rope                      0.18.0                     py_0  
rtree                     0.9.4                    py38_1  
ruamel_yaml               0.15.100         py38h9ed2024_0  
s3transfer                0.3.4              pyhd3eb1b0_0  
scikit-image              0.17.2           py38h81aa140_0  
scikit-learn              0.24.1           py38hb2f4e1b_0  
scipy                     1.6.1            py38h2515648_0  
seaborn                   0.11.1             pyhd3eb1b0_0  
send2trash                1.5.0              pyhd3eb1b0_1  
setuptools                52.0.0           py38hecd8cb5_0  
simplegeneric             0.8.1                    py38_2  
singledispatch            3.6.1           pyhd3eb1b0_1001  
sip                       4.19.8           py38h0a44026_0  
six                       1.15.0           py38hecd8cb5_0  
smmap                     3.0.5              pyhd3eb1b0_0  
snappy                    1.1.8                hb1e8313_0  
sniffio                   1.2.0            py38hecd8cb5_1  
snowballstemmer           2.1.0              pyhd3eb1b0_0  
sortedcollections         2.1.0              pyhd3eb1b0_0  
sortedcontainers          2.3.0              pyhd3eb1b0_0  
soupsieve                 2.2                pyhd3eb1b0_0  
sphinx                    3.5.2              pyhd3eb1b0_0  
sphinxcontrib             1.0                      py38_1  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    1.0.3              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.4              pyhd3eb1b0_0  
sphinxcontrib-websupport  1.2.4                      py_0  
spyder                    4.2.3            py38hecd8cb5_0  
spyder-kernels            1.10.2           py38hecd8cb5_0  
sqlalchemy                1.3.23           py38h9ed2024_0  
sqlite                    3.35.2               hce871da_0  
statsmodels               0.12.2           py38h9ed2024_0  
streamlit                 0.79.0             pyhd8ed1ab_0    conda-forge
sympy                     1.7.1            py38hecd8cb5_0  
tbb                       2020.3               h879752b_0  
tblib                     1.7.0                      py_0  
terminado                 0.9.3            py38hecd8cb5_0  
testpath                  0.4.4              pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tifffile                  2021.3.17          pyhd3eb1b0_1  
tk                        8.6.10               hb0a8c7a_0  
toml                      0.10.2             pyhd3eb1b0_0  
toolz                     0.11.1             pyhd3eb1b0_0  
tornado                   6.1              py38h9ed2024_0  
tqdm                      4.59.0             pyhd3eb1b0_1  
traitlets                 5.0.5              pyhd3eb1b0_0  
typed-ast                 1.4.2            py38h9ed2024_1  
typing_extensions         3.7.4.3            pyha847dfd_0  
tzlocal                   2.1                      py38_0  
ujson                     4.0.2            py38h23ab428_0  
unicodecsv                0.14.1                   py38_0  
unixodbc                  2.3.9                haf1e3a3_0  
uriparser                 0.9.3                h0a44026_1  
urllib3                   1.26.4             pyhd3eb1b0_0  
utf8proc                  2.6.1                h9ed2024_0  
validators                0.18.2             pyhd3eb1b0_0  
watchdog                  1.0.2            py38h9ed2024_1  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py38_1  
werkzeug                  1.0.1              pyhd3eb1b0_0  
wheel                     0.36.2             pyhd3eb1b0_0  
widgetsnbextension        3.5.1                    py38_0  
wrapt                     1.12.1           py38haf1e3a3_1  
wurlitzer                 2.0.1                    py38_0  
xlrd                      2.0.1              pyhd3eb1b0_0  
xlsxwriter                1.3.7              pyhd3eb1b0_0  
xlwings                   0.23.0           py38hecd8cb5_0  
xlwt                      1.3.0                    py38_0  
xmltodict                 0.12.0                     py_0  
xz                        5.2.5                h1de35cc_0  
yaml                      0.2.5                haf1e3a3_0  
yapf                      0.31.0             pyhd3eb1b0_0  
zeromq                    4.3.4                h23ab428_0  
zfp                       0.5.5                h23ab428_4  
zict                      2.0.0              pyhd3eb1b0_0  
zipp                      3.4.1              pyhd3eb1b0_0  
zlib                      1.2.11               h1de35cc_3  
zope                      1.0                      py38_1  
zope.event                4.5.0                    py38_0  
zope.interface            5.2.0            py38h9ed2024_0  
zstd                      1.4.5                h41d2c2f_0 
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : ml-datascience
    active env location : /Users/janbiederbeck/opt/anaconda3/envs/ml-datascience
            shell level : 2
       user config file : /Users/janbiederbeck/.condarc
 populated config files : /Users/janbiederbeck/.condarc
          conda version : 4.9.2
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/janbiederbeck/opt/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/janbiederbeck/opt/anaconda3/pkgs
                          /Users/janbiederbeck/.conda/pkgs
       envs directories : /Users/janbiederbeck/opt/anaconda3/envs
                          /Users/janbiederbeck/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.8 Darwin/20.3.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</details>

**Comment by harishkashyap** [comment]
+1 for this. Streamlit has random errors where the error is thrown even after install of right deps:

from streamlit.cli import main
  File "venv38/lib/python3.8/site-packages/streamlit/__init__.py", line 48, in <module>
    from streamlit.proto.RootContainer_pb2 import RootContainer
  File "venv38/lib/python3.8/site-packages/streamlit/proto/RootContainer_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "venv38/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message

**Comment by randyzwitch** [comment]
Closing this issue, as it is incorporated here:

https://github.com/conda-forge/streamlit-feedstock/blob/main/recipe/meta.yaml#L41

Only thing I could suggest @harishkashyap is maybe try from a completely clean environment? If it happens again, then we've got a separate error from the protobuf issue.

Best,
Randy
